name: Go
on: [push]
jobs:

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:

    - name: Download Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup
      run: make setup

    - name: Get dependencies
      run: make deps

    - name: Generate mocks
      run: |
        go generate

    - name: Test
      run: make test-unit
